-- MySQL Script generated by MySQL Workbench
-- Mon Mar 13 14:49:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`DIM_Arrested_Criminal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DIM_Arrested_Criminal` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DIM_Arrested_Criminal` (
  `idDIM_Arrested_Crinimal` INT NOT NULL,
  `AGE_GROUP` INT NULL,
  `PERP_SEX` VARCHAR(45) NULL,
  `PERP_RACE` VARCHAR(45) NULL,
  PRIMARY KEY (`idDIM_Arrested_Crinimal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DIM_Date`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DIM_Date` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DIM_Date` (
  `idDIM_Date` DATETIME NOT NULL,
  `ARREST_DATE` DATETIME NULL,
  PRIMARY KEY (`idDIM_Date`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DIM_KY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DIM_KY` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DIM_KY` (
  `idDIM_KY` INT NOT NULL,
  `KY_CD` VARCHAR(45) NULL,
  `OFNS_DESC` VARCHAR(45) NULL,
  PRIMARY KEY (`idDIM_KY`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DIM_Law`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DIM_Law` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DIM_Law` (
  `idDIM_Law` INT NOT NULL,
  `LAW_CODE` VARCHAR(45) NULL,
  `LAW_CAT_CD` VARCHAR(45) NULL,
  `JURISDICTION_CODE` VARCHAR(45) NULL,
  PRIMARY KEY (`idDIM_Law`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DIM_Location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DIM_Location` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DIM_Location` (
  `idDIM_LOCATION` INT NOT NULL,
  `ARREST_BORO` VARCHAR(45) NULL,
  `X_COORD_CD` VARCHAR(45) NULL,
  `Y_COORD_CD` VARCHAR(45) NULL,
  `Latitude` VARCHAR(45) NULL,
  `Longitude` VARCHAR(45) NULL,
  PRIMARY KEY (`idDIM_LOCATION`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DIM_PD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DIM_PD` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DIM_PD` (
  `idDIM_PD` INT NOT NULL,
  `PD_CD` VARCHAR(45) NULL,
  `PD_DESC` VARCHAR(45) NULL,
  PRIMARY KEY (`idDIM_PD`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FACT_NYPD_Arrest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`FACT_NYPD_Arrest` ;

CREATE TABLE IF NOT EXISTS `mydb`.`FACT_NYPD_Arrest` (
  `idFact_NYPD_Arrest` INT NOT NULL,
  `ARREST_KEY` INT NULL,
  `DIM_Location_idDIM_LOCATION` INT NOT NULL,
  `DIM_PD_idDIM_PD` INT NOT NULL,
  `DIM_Law_idDIM_Law` INT NOT NULL,
  `DIM_Arrested_Criminal_idDIM_Arrested_Crinimal` INT NOT NULL,
  `DIM_KY_idDIM_KY` INT NOT NULL,
  `DIM_Date_idDIM_Date` DATETIME NOT NULL,
  PRIMARY KEY (`idFact_NYPD_Arrest`),
  INDEX `fk_FACT_NYPD_Arrest_DIM_Location_idx` (`DIM_Location_idDIM_LOCATION` ASC) VISIBLE,
  INDEX `fk_FACT_NYPD_Arrest_DIM_PD1_idx` (`DIM_PD_idDIM_PD` ASC) VISIBLE,
  INDEX `fk_FACT_NYPD_Arrest_DIM_Law1_idx` (`DIM_Law_idDIM_Law` ASC) VISIBLE,
  INDEX `fk_FACT_NYPD_Arrest_DIM_Arrested_Criminal1_idx` (`DIM_Arrested_Criminal_idDIM_Arrested_Crinimal` ASC) VISIBLE,
  INDEX `fk_FACT_NYPD_Arrest_DIM_KY1_idx` (`DIM_KY_idDIM_KY` ASC) VISIBLE,
  INDEX `fk_FACT_NYPD_Arrest_DIM_Date1_idx` (`DIM_Date_idDIM_Date` ASC) VISIBLE,
  CONSTRAINT `fk_FACT_NYPD_Arrest_DIM_Location`
    FOREIGN KEY (`DIM_Location_idDIM_LOCATION`)
    REFERENCES `mydb`.`DIM_Location` (`idDIM_LOCATION`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FACT_NYPD_Arrest_DIM_PD1`
    FOREIGN KEY (`DIM_PD_idDIM_PD`)
    REFERENCES `mydb`.`DIM_PD` (`idDIM_PD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FACT_NYPD_Arrest_DIM_Law1`
    FOREIGN KEY (`DIM_Law_idDIM_Law`)
    REFERENCES `mydb`.`DIM_Law` (`idDIM_Law`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FACT_NYPD_Arrest_DIM_Arrested_Criminal1`
    FOREIGN KEY (`DIM_Arrested_Criminal_idDIM_Arrested_Crinimal`)
    REFERENCES `mydb`.`DIM_Arrested_Criminal` (`idDIM_Arrested_Crinimal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FACT_NYPD_Arrest_DIM_KY1`
    FOREIGN KEY (`DIM_KY_idDIM_KY`)
    REFERENCES `mydb`.`DIM_KY` (`idDIM_KY`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FACT_NYPD_Arrest_DIM_Date1`
    FOREIGN KEY (`DIM_Date_idDIM_Date`)
    REFERENCES `mydb`.`DIM_Date` (`idDIM_Date`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

